### ISSUE TITLE
Is Bootstrap required in order to send data to Coiote?

### ISSUE THREAD

**Issue by MLopezJ** [MLopezJ/trace-anjay#2]
The official [documentation (pag 15)](https://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.pdf) says:
 > The LwM2M Bootstrap-Server is a server responsible for provisioning essential information, including credentials, into the LwM2M Client to enable the LwM2M Client to perform the "Register" operation with one or more LwM2M Servers. Very often, the LwM2M Bootstrap-Server is the first LwM2M entity an LwM2M Client interacts with. The Bootstrap Interface is the only interface used between the LwM2M Client and the LwM2M Bootstrap-Server.

Which seems pretty clear about the important of it. However, the bootstrap awareness is happening many steps latter in the tutorial https://avsystem.github.io/Anjay-doc/AdvancedTopics/AT-CustomObjects/AT_CO_BootstrapAwareness.html, which gives the impression it is not required for the behavior I'm looking for (show values in web app)

**Comment by MLopezJ** [comment]
> The Bootstrap Interface defines the tools for the LwM2M Bootstrap Server to provision the LwM2M Client with initial information needed to “register” with the LwM2M Server. 

[Here](https://www.avsystem.com/crashcourse/lwm2m/#:~:text=The%20Bootstrap%20Interface%20defines%20the%20tools%20for%20the%20LwM2M%20Bootstrap%20Server%20to%20provision%20the%20LwM2M%20Client%20with%20initial%20information%20needed%20to%20%E2%80%9Cregister%E2%80%9D%20with%20the%20LwM2M%20Server.) is understood that the bootstraping is required to comunicate properly with the server, but I can not see any bootstraping steps in the [Anjay's basics examples](https://avsystem.github.io/Anjay-doc/BasicClient.html)  . 

Is bootstraping happening in Anjay? If so, how?

**Comment by MLopezJ** [comment]
From [stack overflow](https://stackoverflow.com/questions/63986860/lwm2m-protocol-is-bootstrap-server-mandatory): 

### is bootstrap server mandatory?

 The LwM2M Bootstrap Server is not necessary if the LwM2M Client supports the Factory Bootstrap.

**Comment by MLopezJ** [comment]
# Factory Bootstrap

This type of bootstraping basically means to hardcode information about the LwM2M server. It is not a good practice because you will need physical access to devices in order to change credentials or server URL, but in the context of the device simulator it doesnt matter because you always have access to the device and there are not used credentials. 


https://medium.com/@vrmvrm/device-key-distribution-with-lightweight-m2m-36cdc12e5711

**Comment by MLopezJ** [comment]
How to implement Factory Bootstrap?

I'm assunming a way to implement Factory Bootstrap is to set the following values manuallly:

```
{
    "servers": {
        "1": {
            "shortId": "1"
        }
    },
    "security": {
        "1": {
            "uri": "coap://[2001:db8::2]:5683/",
            "securityMode": "NO_SEC",
            "serverId": "1"
        }
    }
}
```
https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v15.0.0%2Fiot_sdk_app_lwm2m_client.html

**Comment by MLopezJ** [comment]
[Here](https://cumulocity.com/guides/protocol-integration/lwm2m/#registration-of-no_sec-devices) is said that **5683** is the port for unsecure bootstrap connection and **5783** is the one for unsecure direct server connection. 

Double check on port used by Anjay.

**Comment by MLopezJ** [comment]
# TEST

Connect to https://leshan.eclipseprojects.io/#/server using https://github.com/MLopezJ/trace-anjay/issues/2#issuecomment-1505197236

**Comment by MLopezJ** [comment]
# TODO
- [ ] Check `Anjay/include_public/anjay/security.h` and `Anjay/include_public/anjay/server.h` . Boths files are required in `BC-MandatoryObjects` example form Anjay. 
- [ ] trace `BC-MandatoryObjects` with WireShark
- [ ] Try to connect `BC-MandatoryObjects` with Coiote
- [ ] Try to connect `BC-MandatoryObjects` with Leshan and 'steal' values from Objects to perform Factory Bootstrap

**Comment by MLopezJ** [comment]
# Is Bootstrap required in order to send data to Coiote? 

Answer is no. You can connect to Coiote or any other LwM2M server using the Factory Bootstrap configuration.
